<script setup lang="ts">
    import { computed, ref, nextTick } from "vue";
    import { katexMacros } from "../components/katexMacros";
    import EquationUtility from "./../components/EquationUtility.vue";
    import { HelpElement } from "./helpElement";
    import helpDatabaseImport from "./helpDatabase.json";
    const helpDatabase = helpDatabaseImport as HelpElement[];

    // import the examples into memory storage
    import { OperatorConfig, PermanenceStorageModes, generateOperatorConfig, usePermanenceStore } from "./../functions";
    const permanenceStore = usePermanenceStore();
    permanenceStore.setStorageModeTo(PermanenceStorageModes.memory);

    const elements = computed((): { element: HelpElement; config: OperatorConfig }[] => {
        let outArray: { element: HelpElement; config: OperatorConfig }[] = [];

        // normally un-nice to do in computed, but this only is executed once, because the only input is a json import
        helpDatabase.forEach((elem) => {
            for (const uuid in elem.storage) {
                const value = elem.storage[uuid];
                if (value != undefined) {
                    permanenceStore.abstractStoreImplementationSet(uuid, value);
                }
            }

            outArray.push({
                config: generateOperatorConfig(elem.mainUuid, elem.variablesUuid, elem.macrosUuid),
                element: elem,
            });
        });

        return outArray;
    });

    const VITE_RENDER_ROUTER_LINKS = import.meta.env.VITE_RENDER_ROUTER_LINKS != "0";
    const macros = computed((): string => {
        let outMacros = [] as string[];

        Object.keys(katexMacros).forEach((macroKey) => {
            const macroContent = (katexMacros as { [key: string]: string })[macroKey];

            outMacros.push(`\\newcommand{${macroKey}}{${macroContent}}`);
        });

        return outMacros.join("\n");
    });

    function kebabCase(inputString: string) {
        return inputString.toLowerCase().replace(/[ _]/g, "-");
    }

    const helpFilterInput = ref("");
    const helpFilter = computed((): string => {
        render.value = false;
        nextTick(() => {
            render.value = true;
        });
        return helpFilterInput.value.toLowerCase();
    });

    const displayElement = computed((): { [key: string]: boolean } => {
        let outArray: { [key: string]: boolean } = {};

        elements.value.forEach((el) => {
            outArray[el.element.title] =
                el.element.title.toLowerCase().includes(helpFilter.value) ||
                el.element.description.toLowerCase().includes(helpFilter.value);
        });

        return outArray;
    });

    const vHighlight = {
        mounted: (el: any) => {
            if (helpFilter.value != "") {
                const regex = new RegExp(`(${helpFilter.value})`, "gi");
                el.innerHTML = el.innerHTML.replace(regex, '<span class="highlighted">$1</span>');
            }
        },
    };
    const render = ref(true);
</script>

<template>
    <h1>Math Manipulator: Help Playground</h1>

    <p v-if="VITE_RENDER_ROUTER_LINKS">Head Back to the <router-link to="/">Welcome Page</router-link></p>

    <p>Here a bunch of pre-configured operations and effects are presented.</p>
    <p>The help is interactive. Feel free to make changes and experiment at any point.</p>
    <p>Help can be reset with refreshing the page</p>

    <h3>Search in Help:</h3>

    Filter headings and descriptions -> <input type="text" v-model="helpFilterInput" />
    <br />
    <br />
    <template v-for="elem in elements">
        <div
            :style="{
                display: !displayElement[elem.element.title] ? 'none' : '',
            }"
        >
            <h2 v-highlight :id="kebabCase(elem.element.title)" v-if="render">{{ elem.element.title }}</h2>
            <div class="help-indented">
                <p v-highlight style="white-space: pre-line" v-if="render">{{ elem.element.description }}</p>
                <EquationUtility
                    :config="elem.config"
                    :show-variables="elem.element.showVariables"
                    :show-macros="elem.element.showMacros"
                />
            </div>
        </div>
    </template>
    <h2 v-highlight v-if="render">Extra Macros you will need to copy-paste</h2>
    <div class="help-indented">
        <p style="margin-bottom: 1em" v-highlight v-if="render">
            To insert the LaTeX output generated by the tool, put it into math mode ($...$) and make sure to add the provided
            macro definitions to the preamble.
        </p>

        <pre style="margin-left: 4em">{{ macros }}</pre>
    </div>
    <div style="width: 100%; min-height: 40vh"></div>
</template>

<style scoped>
    .help-indented {
        padding-left: 1.5em;
    }
</style>

<style>
    .highlighted {
        background-color: yellow;
    }
</style>
